-- Write your MySQL query statement below
WITH CTE AS (
SELECT DENSE_RANK() OVER (ORDER BY SALARY DESC) AS O_ID, SALARY FROM  EMPLOYEE)
SELECT ISNULL((SELECT TOP 1 SALARY FROM CTE WHERE O_ID = 2),NULL) AS SecondHighestSalary ;