/* Write your T-SQL query statement below */
SELECT A.ID as id, B.STUDENT AS student FROM SEAT A INNER JOIN SEAT B ON A.ID+1 = B.ID WHERE A.ID%2 = 1
UNION
SELECT A.ID,B.Student AS STUDENT FROM SEAT A LEFT JOIN SEAT B ON A.ID-1 = B.ID WHERE A.ID%2 = 0
UNION 
SELECT ID, STUDENT FROM SEAT WHERE ID = (SELECT MAX(ID) FROM SEAT) AND ID%2 =1;
